"""empty message

Revision ID: 21f3ba46c602
Revises: 34bf0cd0b22e
Create Date: 2015-05-03 14:13:31.955440

"""

# revision identifiers, used by Alembic.
revision = '21f3ba46c602'
down_revision = '34bf0cd0b22e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('day_id', sa.String(length=4), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'day_id')
    ### end Alembic commands ###
