"""empty message

Revision ID: 258cb520bf38
Revises: 2a983c0c392e
Create Date: 2015-04-24 17:22:27.185800

"""

# revision identifiers, used by Alembic.
revision = '258cb520bf38'
down_revision = '2a983c0c392e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=300), nullable=True),
                    sa.Column('creation_date', sa.DateTime(), nullable=False),
                    sa.Column('status', sa.String(length=128), nullable=False, server_default='new'),
                    sa.PrimaryKeyConstraint('id')
                    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reports')
    ### end Alembic commands ###
