"""empty message

Revision ID: 2a25d388223
Revises: 258cb520bf38
Create Date: 2015-04-24 18:35:53.228802

"""

# revision identifiers, used by Alembic.
revision = '2a25d388223'
down_revision = '258cb520bf38'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('report_state', sa.String(length=128), nullable=False, server_default='new'))
    op.alter_column('reports', 'name',
                    existing_type=mysql.VARCHAR(length=300),
                    nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reports', 'name',
                    existing_type=mysql.VARCHAR(length=300),
                    nullable=False)
    op.drop_column('cards', 'report_state')
    ### end Alembic commands ###
