"""empty message

Revision ID: 34bf0cd0b22e
Revises: 484e0a040f34
Create Date: 2015-04-30 13:36:57.765415

"""

# revision identifiers, used by Alembic.
revision = '34bf0cd0b22e'
down_revision = '484e0a040f34'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cards_history', 'user_id',
                    existing_type=mysql.INTEGER(display_width=11),
                    nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cards_history', 'user_id',
                    existing_type=mysql.INTEGER(display_width=11),
                    nullable=False)
    ### end Alembic commands ###
