"""empty message

Revision ID: 3b348d995e9c
Revises: 4a7215f63b31
Create Date: 2015-07-23 14:27:26.120536

"""

# revision identifiers, used by Alembic.
revision = '3b348d995e9c'
down_revision = '4a7215f63b31'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('logo', sa.Text(), nullable=True))
    op.add_column('orders', sa.Column('name', sa.String(length=512), nullable=True))
    op.add_column('orders', sa.Column('photo', sa.Text(), nullable=True))
    op.add_column('orders', sa.Column('position', sa.String(length=512), nullable=True))
    op.alter_column('orders', 'user_email',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
    op.create_unique_constraint(None, 'orders', ['user_email'])
    op.drop_column('orders', 'content')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('content', mysql.VARCHAR(length=512), nullable=True))
    op.drop_constraint(None, 'orders', type_='unique')
    op.alter_column('orders', 'user_email',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
    op.drop_column('orders', 'position')
    op.drop_column('orders', 'photo')
    op.drop_column('orders', 'name')
    op.drop_column('orders', 'logo')
    ### end Alembic commands ###
