"""empty message

Revision ID: 4316a2f6a6ce
Revises: 52abcfad3737
Create Date: 2015-05-10 16:48:27.208447

"""

# revision identifiers, used by Alembic.
revision = '4316a2f6a6ce'
down_revision = '52abcfad3737'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('order_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cards', 'orders', ['order_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cards', type_='foreignkey')
    op.drop_column('cards', 'order_id')
    ### end Alembic commands ###
