"""empty message

Revision ID: 4750b8ddc267
Revises: 17f5cce046f1
Create Date: 2015-05-10 15:23:55.871868

"""

# revision identifiers, used by Alembic.
revision = '4750b8ddc267'
down_revision = '17f5cce046f1'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('user_email', sa.String(length=128), nullable=False))
    op.add_column('orders', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_column('orders', 'mobispot_user_email')
    op.drop_column('orders', 'mobispot_user_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('mobispot_user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('mobispot_user_email', mysql.VARCHAR(length=128), nullable=False))
    op.drop_column('orders', 'user_id')
    op.drop_column('orders', 'user_email')
    ### end Alembic commands ###
