"""empty message

Revision ID: 481d60b53969
Revises: dd3e88c4b43
Create Date: 2015-05-24 23:04:47.830423

"""

# revision identifiers, used by Alembic.
revision = '481d60b53969'
down_revision = 'dd3e88c4b43'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'image',
                    existing_type=mysql.VARCHAR(length=512),
                    nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'image',
                    existing_type=mysql.VARCHAR(length=512),
                    nullable=False)
    ### end Alembic commands ###
