"""empty message

Revision ID: 484e0a040f34
Revises: 2819329c10a3
Create Date: 2015-04-26 19:54:59.687173

"""

# revision identifiers, used by Alembic.
revision = '484e0a040f34'
down_revision = '2819329c10a3'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('report_id', sa.Integer(), nullable=True))
    op.drop_index('ix_cards_report_state', table_name='cards')
    op.create_foreign_key(None, 'cards', 'reports', ['report_id'], ['id'])
    op.drop_column('cards', 'report_state')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('report_state', mysql.VARCHAR(length=128), server_default=sa.text(u"'new'"), nullable=False))
    op.drop_constraint(None, 'cards', type_='foreignkey')
    op.create_index('ix_cards_report_state', 'cards', ['report_state'], unique=False)
    op.drop_column('cards', 'report_id')
    ### end Alembic commands ###
