"""empty message

Revision ID: 4a7215f63b31
Revises: 481d60b53969
Create Date: 2015-07-23 14:07:56.853419

"""

# revision identifiers, used by Alembic.
revision = '4a7215f63b31'
down_revision = '481d60b53969'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('content', sa.String(length=512), nullable=True))
    op.drop_column('orders', 'image')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('image', mysql.VARCHAR(length=512), nullable=True))
    op.create_index('user_email', 'orders', ['user_email'], unique=True)
    op.create_unique_constraint(u'user_email', 'orders', ['user_email'])
    op.alter_column('orders', 'user_email',
                    existing_type=mysql.VARCHAR(length=128),
                    nullable=False)
    op.drop_column('orders', 'content')
    ### end Alembic commands ###
