"""empty message

Revision ID: 571bc3798427
Revises: 4316a2f6a6ce
Create Date: 2015-05-10 17:57:06.531297

"""

# revision identifiers, used by Alembic.
revision = '571bc3798427'
down_revision = '4316a2f6a6ce'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('update_date', sa.DateTime(), nullable=True))
    op.add_column('orders', sa.Column('update_date', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'update_date')
    op.drop_column('cards', 'update_date')
    ### end Alembic commands ###
