"""empty message

Revision ID: 59c30355dac3
Revises: 21f3ba46c602
Create Date: 2015-05-10 15:00:42.686396

"""

# revision identifiers, used by Alembic.
revision = '59c30355dac3'
down_revision = '21f3ba46c602'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('mobispot_user_id', sa.Integer(), nullable=False),
                    sa.Column('creation_date', sa.DateTime(), nullable=False),
                    sa.Column('status', sa.String(length=128), nullable=False, server_default='new'),
                    sa.PrimaryKeyConstraint('id')
                    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    ### end Alembic commands ###
