"""empty message

Revision ID: e030541c924
Revises: 3b348d995e9c
Create Date: 2015-09-02 10:09:49.014222

"""

# revision identifiers, used by Alembic.
revision = 'e030541c924'
down_revision = '3b348d995e9c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('address', sa.String(length=128), nullable=False),
    sa.Column('zip', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'cards', sa.Column('campus_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cards', 'campus', ['campus_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cards', type_='foreignkey')
    op.drop_column(u'cards', 'campus_id')
    op.drop_table('campus')
    ### end Alembic commands ###
